# Generated by Django 4.2.5 on 2023-11-03 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Invent', '0002_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_des', models.CharField(max_length=50)),
                ('product_quantity', models.IntegerField(max_length=100)),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Invent.cate')),
                ('room_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Invent.room')),
            ],
        ),
    ]
