# Generated by Django 4.2.5 on 2023-11-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invent', '0003_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='Product_quantiry',
            field=models.IntegerField(default=50),
        ),
    ]
