# Generated by Django 4.2.5 on 2023-11-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invent', '0005_rename_product_quantiry_product_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Product_quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='product_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
