# Generated by Django 4.2.5 on 2023-11-03 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Invent', '0007_alter_product_category_name_alter_product_room_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Invent.cate'),
        ),
        migrations.AlterField(
            model_name='product',
            name='room_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Invent.room'),
        ),
    ]
