# Generated by Django 4.2.5 on 2023-11-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invent', '0008_alter_product_category_name_alter_product_room_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
